name: Build with Maven

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn install
    - name: Upload Artifact to GitHub Action
      uses: actions/upload-artifact@v3
      with: 
        name: GlowAPI
        path: target/GlowAPI*.jar
